language: scala
sudo: false

scala:
  - 2.11.12
  - 2.12.9
  # - 2.13.0

jdk:
  - openjdk8
  - openjdk11

env:
  - SCALAJS_VERSION=0.6.28
  # - SCALAJS_VERSION=1.0.0-M8


script:
  - sbt ++$TRAVIS_SCALA_VERSION outwatch/test
  - sbt docs/mdoc
  - sbt docs/docusaurusCreateSite

deploy:
  provider: pages
  skip-cleanup: true
  # Set in the settings page of your repository, as a secure variable
  github-token: $GITHUB_TOKEN  
  keep-history: true
  local-dir: ./website/build/outwatch
  target-branch: gh-pages
  on:
    branch: master

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
before_cache:
  # Tricks to avoid unnecessary cache updates
  # https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html#Caching
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
